version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: myKeycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - "8080:8080"

