spring:
  application:
    name: msusers
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contabilidade
    username: rmv
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      generate-dll: true
      show-sql: true
server:
  port: 8081